### ISSUE TITLE
Prototyping settings

### ISSUE THREAD

**Issue by oddjones** [jake-figma/component-inspector#4]
Hey Jake - so this is such an exciting project! It's really got me thinking. We have a product which renders JSON in a proprietary format for each component in a journey - I can see myself creating a setting for my own "language" which will export the JSON for each page in my journmey - but the bit that I can't seem to figure out is how to view an instance's prototyping settings - If I could see where the instance links to then I could export my whole journey as a JSON file and (in effect) create a WYSIWYG editor for my product in FIgma (especially now Figma's prototyping allows for conditionals etc) - which would be utterly awesome... Is there any documentation anywhere for this? (I've tried a couple of JSON exporter plugins, but can't seem to see anything related to prototyping anywhere

**Comment by jake-figma** [comment]
thanks for reaching out! best place for convos like this is our [Discord](https://discord.gg/figma) or [Forum](https://forum.figma.com/c/plugin-widget-api/)! 

To answer your question, check out `reactions` in the plugin API: https://www.figma.com/plugin-docs/api/Reaction
